config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'ask', to: 'map#ask'

  get 'show', to: 'map#show'

  get 'academic_interest', to: 'pages#academic_interest'

  get 'personal_interest', to: 'pages#personal_interest'

  get 'about_me', to: 'pages#about_me'

  get 'home', to: 'pages#home'

  resources :layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/layout.rb
class Layout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_action :set_layout, only: [:show, :edit, :update, :destroy]

  # GET /layouts
  # GET /layouts.json
  def index
    @layouts = Layout.all
  end

  # GET /layouts/1
  # GET /layouts/1.json
  def show
  end

  # GET /layouts/new
  def new
    @layout = Layout.new
  end

  # GET /layouts/1/edit
  def edit
  end

  # POST /layouts
  # POST /layouts.json
  def create
    @layout = Layout.new(layout_params)

    respond_to do |format|
      if @layout.save
        format.html { redirect_to @layout, notice: 'Layout was successfully created.' }
        format.json { render :show, status: :created, location: @layout }
      else
        format.html { render :new }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layouts/1
  # PATCH/PUT /layouts/1.json
  def update
    respond_to do |format|
      if @layout.update(layout_params)
        format.html { redirect_to @layout, notice: 'Layout was successfully updated.' }
        format.json { render :show, status: :ok, location: @layout }
      else
        format.html { render :edit }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layouts/1
  # DELETE /layouts/1.json
  def destroy
    @layout.destroy
    respond_to do |format|
      format.html { redirect_to layouts_url, notice: 'Layout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
      @layout = Layout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layout_params
      params.require(:layout).permit(:title, :subtitle, :text, :body, :image)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def ask
  end

  def show
  	@food = params[:food]
  	@place = params[:place]
  	@map = "https://www.google.com/maps/embed/v1/search?key=#{ENV['GOOGLE_API_KEY']}
    &q=best+place+in+#{@place}+Earth+for+#{@food}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def academic_interest
  end

  def personal_interest
  end

  def about_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_form.html.erb
<%= form_with(model: layout, local: true) do |form| %>
  <% if layout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(layout.errors.count, "error") %> prohibited this layout from being saved:</h2>

      <ul>
      <% layout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :layout_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :layout_subtitle %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :layout_text %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :layout_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :layout_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">BV</a>
    </div>
      <li class="active"><%= link_to 'Home', home_path %></li>
      <li><%= link_to 'Academic Interest', academic_interest_path %></li>
 	  <li><%= link_to 'Personal Interest', personal_interest_path %></li>
	  <li><%= link_to 'About Me', about_me_path %></li>
	  <li><%= link_to 'Google Maps API (delete when not needed)', ask_path %></li>
  </div>
</nav>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  	<%= render 'layouts/navbar' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/edit.html.erb
<h1>Editing Layout</h1>

<%= render 'form', layout: @layout %>

<%= link_to 'Show', @layout %> |
<%= link_to 'Back', layouts_path %>

app/views/layouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Layouts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Text</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @layouts.each do |layout| %>
      <tr>
        <td><%= layout.title %></td>
        <td><%= layout.subtitle %></td>
        <td><%= layout.text %></td>
        <td><%= layout.body %></td>
        <td><%= layout.image %></td>
        <td><%= link_to 'Show', layout %></td>
        <td><%= link_to 'Edit', edit_layout_path(layout) %></td>
        <td><%= link_to 'Destroy', layout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Layout', new_layout_path %>

app/views/layouts/new.html.erb
<h1>New Layout</h1>

<%= render 'form', layout: @layout %>

<%= link_to 'Back', layouts_path %>

app/views/layouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @layout.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @layout.subtitle %>
</p>

<p>
  <strong>Text:</strong>
  <%= @layout.text %>
</p>

<p>
  <strong>Body:</strong>
  <%= @layout.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @layout.image %>
</p>

<%= link_to 'Edit', edit_layout_path(@layout) %> |
<%= link_to 'Back', layouts_path %>

app/views/map/ask.html.erb
<h1>Map#ask</h1>
<p>Find me in app/views/map/ask.html.erb</p>

<center>
	<!Sets up form>
<%= form_tag show_path, method: "get", html: { class: "form" } do %>

	<div class="form_group col-sm-6 col-md-offset-3">
		<%= text_field_tag(:place, "", placeholder: "Enter Neighborhood", class: "form-control")%>
	</div>

	<div class="form_group col-sm-6 col-md-offset-3">
		<%= text_field_tag(:food, "", placeholder: "Enter food", class: "form-control")%>
	</div>

	<center> 
		<div class="form_group text-center">
			<%=submit_tag "Search", class: "gmaps-btn btn btn-outline-info text-align: center;"%>
				<% end %>
		</div>
	</center>
</center>

app/views/map/show.html.erb
<h1><%= @food %></h1>

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="<%= @map %>">
</iframe>

app/views/pages/about_me.html.erb
<h1>Pages#about_me</h1>
<p>Find me in app/views/pages/about_me.html.erb</p>

app/views/pages/academic_interest.html.erb
<h1>Pages#academic_interest</h1>
<p>Find me in app/views/pages/academic_interest.html.erb</p>

app/views/pages/home.html.erb
<h1 align="center">Braden Vaccari</h1>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="coolskull.jpg" alt="..." style="width:100%;">
      </div>

      <div class="item">
        <img src="coolfox.jpg" alt="..." style="width:100%;">
      </div>
    
      <div class="item">
        <img src="cool.jpg" alt="..." style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/pages/personal_interest.html.erb
<h1>Pages#personal_interest</h1>
<p>Find me in app/views/pages/personal_interest.html.erb</p>